apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: github-regcred
spec:
  encryptedData:
    .dockerconfigjson: AgAO7hHLCM1TAUmSODXaMAoikYMZRm32S28be22vj2mtCeXuIoBG78H12tTE7L+sckXSIBo/W9CtH+TXB77phx6enQwO38MG2pej2d+mF7M/hfgRUsSpcjXONmw5Cxv8MUZkK9t8woIAJ9qrIMjkQZkpaaByRzMHJxD0IGjBPNBedF7KxB7JyW3nIWNgyAwhWp2FcN2LCmxksrYR7tFKVzGThN6XB/ocCW9BXOdl1eZNp2mJVtFopdOOvtrg9l3/6ekBIPlxpBtmqmCiJpLKOw6OnbbMFKKk6SaoXQJ+kT8W0k2c+RU9OVSSy/mff2vVZERZIROAPylO1RkDiEyUm9gpQoAxGnlC8FGahRGWj29na/N/SCGoaNMmpj8i4cO9brLou3poO5vhqt15Xy7N4QkTygsIjfPYBlEAm5c+ERY8F/CaLVm5xsdhgAraPQSnrcrU7ps1LZJGLjpoXw+dAVOQ/EpG1scktytzQManUAMZPLAWPLsODogCXB4UAD8BaucvLOgWfb218CW254PdDPiGA6xVnn0HWJAwMUnKi2BsgLJDZE9l2Gs0ZffCaUomBZ+Iv2Be5JBvUvxoJzC/Si8HrrWGCxAg6k7+mchEnZN7EB/wRH8Pjz3cQsBVaG7/t7466vqjCLEIHWHEKguIiut3kvF7sXh3MuTxSP4Md8cLS0BKb+AjM4dl/nm3X+ScJ4OIIfvL8fac9U975be7I1e8DzybtwKT5pxwDwz42XlFyb3lCR3UK3bqFdKIMjWU4Xit9aBH1HrZ8xPFyyGms6ok2mH2Iw/uyG+rGz6XavNInfn6hx/8hzzu6m9Xjfq9CbTWGYSBWSNSZr3u86ldM9otdSWRWnLh8JsFS2cGQcXL4einQhB6Y9TsDe0bpT22ui40coLGvx0wX6Y84g0IWclj8d+OUe9nxXEcEZRyfj2TuZH+7PRyKBI8
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: github-regcred
    type: kubernetes.io/dockerconfigjson

