apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: sample-secret
spec:
  encryptedData:
    password: AgCrc1gr2f18Zl5PAxtZcOnfgzYoRoI5c90NlXzwW1XzPYHK5GF12Xs9iLEXfMJ7+LAgHa61E/+BwoASO58QCEMT0kGbb0ZthgFIf9h5ZcfjQOEzM5Q2W9t4iAkGgF4TnMA42+xNFtJP6B6jbnVshS1UpGZImWZFLQI0IT6URyqy7MDt54yAauGUbviml+t/5iNBaI83xnvsK443RGlCRJIFDAeXxa6PHR9gSIvT44Hod6OvHtC0EUgviCVbOi9LxnNf1fpnt3RYdRXtLxoGXqXaIB1S1rMK27nh4hoN3AhkNjo2VSAlzBNM1cy1sjtPvJtbu7inVZpXtjIywaBUGDT2Dj4IVameqI2OoqtTrl6GDQSyXtEWvYqu7X1turUT2gJMNswwiJzeR+mAGTQrkmSHxR9DyxdZ4fT/LaSQRFuLouuEFxOD9/8pJ/BJcaDmsQqBWaCenglIn8xrz5DjVAr2qZDwC6W/SLvzuvLBtbcO7Td4w/MbyB9OZhV6jypp1usFNr427S/kdPZm2BjYf6bF3l/nLEtjGID9sYf911hZne4zs6SXOWasQ7HKvHYYSI7JfE70Jorg/vhKWmZKX7xFzauXDH967ws0c/SsAhxgxoCQK7TCuT2yCHeHrdw/ccM7ReQDi4gbkGRqWjvJha/8AAWR12R3FCd9JuzH8qFFZ4zi1cAxkhgPpMIfZhPvMwva+mDd2BA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: sample-secret

